upgrade to Arrow 0.10.0 and Spark 2.4.0
twosigma/flint pull request #70
Opened 2019-06-26 00:09 UTC by hungtantran

2019-06-26 19:52 UTC, icexelloss commented on build.sbt
> -  val spark = sys.props.getOrElse("spark.version", default = "2.3.0")
Can you update this to 2.4.3 and the tests?

2019-06-26 19:53 UTC, icexelloss commented on src/main/scala/com/twosigma/flint/arrow/ArrowConverters.scala
> -    context.addTaskCompletionListener { _ =>
Let's revert this change. This is a Scala 12 change.

2019-06-26 19:53 UTC, icexelloss commented on src/main/scala/com/twosigma/flint/rdd/OrderedRDD.scala
> -        tc.addTaskCompletionListener((_) => iter.close())
Let's revert these two changes. These are Scala 12 changes.

2019-06-26 19:54 UTC, icexelloss requested changes
Looks at high level. Let's fix a few minor issues and then merge.

2019-08-05 21:40 UTC, icexelloss approved these changes

2019-08-05 21:40 UTC, merged

2020-06-01 19:16 UTC, mattomatic commented
This commit should close https://github.com/twosigma/flint/issues/63